[2021-10-09 06:18:39,233] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: v2_context.t0 2021-10-08T00:00:00+00:00 [queued]>
[2021-10-09 06:18:39,240] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: v2_context.t0 2021-10-08T00:00:00+00:00 [queued]>
[2021-10-09 06:18:39,240] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-10-09 06:18:39,240] {taskinstance.py:1095} INFO - Starting attempt 1 of 1
[2021-10-09 06:18:39,240] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-10-09 06:18:39,250] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): t0> on 2021-10-08T00:00:00+00:00
[2021-10-09 06:18:39,252] {standard_task_runner.py:52} INFO - Started process 546 to run task
[2021-10-09 06:18:39,255] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'v2_context', 't0', '2021-10-08T00:00:00+00:00', '--job-id', '353', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/v2_context.py', '--cfg-path', '/tmp/tmp3ioty90e', '--error-file', '/tmp/tmp40lff3pu']
[2021-10-09 06:18:39,255] {standard_task_runner.py:77} INFO - Job 353: Subtask t0
[2021-10-09 06:18:39,282] {logging_mixin.py:109} INFO - Running <TaskInstance: v2_context.t0 2021-10-08T00:00:00+00:00 [running]> on host a6cf1bcf3ec3
[2021-10-09 06:18:39,329] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=v2_context
AIRFLOW_CTX_TASK_ID=t0
AIRFLOW_CTX_EXECUTION_DATE=2021-10-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-08T00:00:00+00:00
[2021-10-09 06:18:39,329] {logging_mixin.py:109} INFO - 2021-10-08
[2021-10-09 06:18:39,330] {python.py:151} INFO - Done. Returned value was: None
[2021-10-09 06:18:39,338] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=v2_context, task_id=t0, execution_date=20211008T000000, start_date=20211009T061839, end_date=20211009T061839
[2021-10-09 06:18:39,386] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-10-09 06:18:39,410] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
