[2021-09-05 13:29:20,846] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: airflow-delete-broken-dags.delete_broken_dag_files 2021-09-04T00:00:00+00:00 [queued]>
[2021-09-05 13:29:20,859] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: airflow-delete-broken-dags.delete_broken_dag_files 2021-09-04T00:00:00+00:00 [queued]>
[2021-09-05 13:29:20,860] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-05 13:29:20,860] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-09-05 13:29:20,860] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-05 13:29:20,880] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): delete_broken_dag_files> on 2021-09-04T00:00:00+00:00
[2021-09-05 13:29:20,885] {standard_task_runner.py:52} INFO - Started process 6791 to run task
[2021-09-05 13:29:20,888] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'airflow-delete-broken-dags', 'delete_broken_dag_files', '2021-09-04T00:00:00+00:00', '--job-id', '232', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/airflow-delete-broken-dags.py', '--cfg-path', '/tmp/tmpv361r1ft', '--error-file', '/tmp/tmpflg76_67']
[2021-09-05 13:29:20,889] {standard_task_runner.py:77} INFO - Job 232: Subtask delete_broken_dag_files
[2021-09-05 13:29:20,934] {logging_mixin.py:109} INFO - Running <TaskInstance: airflow-delete-broken-dags.delete_broken_dag_files 2021-09-04T00:00:00+00:00 [running]> on host 2bce3265bb98
[2021-09-05 13:29:21,001] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=operations
AIRFLOW_CTX_DAG_ID=airflow-delete-broken-dags
AIRFLOW_CTX_TASK_ID=delete_broken_dag_files
AIRFLOW_CTX_EXECUTION_DATE=2021-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-04T00:00:00+00:00
[2021-09-05 13:29:21,001] {airflow-delete-broken-dags.py:56} INFO - Starting to run Clear Process
[2021-09-05 13:29:21,002] {airflow-delete-broken-dags.py:61} INFO - Running on Machine with Host Name: 2bce3265bb98
[2021-09-05 13:29:21,002] {airflow-delete-broken-dags.py:62} INFO - Running on Machine with IP: 172.20.0.3
[2021-09-05 13:29:21,002] {airflow-delete-broken-dags.py:68} INFO - Configurations:
[2021-09-05 13:29:21,002] {airflow-delete-broken-dags.py:69} INFO - enable_delete:            True
[2021-09-05 13:29:21,002] {airflow-delete-broken-dags.py:70} INFO - session:                  <sqlalchemy.orm.session.Session object at 0x7f59f8bc87f0>
[2021-09-05 13:29:21,002] {airflow-delete-broken-dags.py:71} INFO - 
[2021-09-05 13:29:21,009] {airflow-delete-broken-dags.py:75} INFO - Process will be removing broken DAG file(s) from the file system:
[2021-09-05 13:29:21,009] {airflow-delete-broken-dags.py:80} INFO - Process will be Deleting 0 DAG file(s)
[2021-09-05 13:29:21,009] {airflow-delete-broken-dags.py:85} INFO - Performing Delete...
[2021-09-05 13:29:21,010] {airflow-delete-broken-dags.py:90} INFO - Finished Performing Delete
[2021-09-05 13:29:21,010] {airflow-delete-broken-dags.py:94} INFO - Finished
[2021-09-05 13:29:21,010] {python.py:151} INFO - Done. Returned value was: None
[2021-09-05 13:29:21,016] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=airflow-delete-broken-dags, task_id=delete_broken_dag_files, execution_date=20210904T000000, start_date=20210905T132920, end_date=20210905T132921
[2021-09-05 13:29:21,060] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-05 13:29:21,089] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
